[
  {
    listing_id: 1,
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 2,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 3,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 5,
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 7,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 8,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 9,
    guests: 7,
    beds: 7,
    bath: 2,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 10,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 11,
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 13,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 14,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 15,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 17,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 18,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 19,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 21,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 26,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 27,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 28,
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 29,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 31,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 33,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 34,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 35,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 36,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 38,
    guests: 3,
    beds: 2,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 40,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 41,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 42,
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 45,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 46,
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 49,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 51,
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 52,
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 54,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 56,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 60,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 63,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 64,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 65,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 68,
    guests: 14,
    beds: 12,
    bath: 3,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 70,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 72,
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 73,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 75,
    guests: 7,
    beds: 6,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 76,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 77,
    guests: 8,
    beds: 7,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 79,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 81,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 84,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 87,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 89,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 91,
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 92,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 93,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 95,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 96,
    guests: 7,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 97,
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 98,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 99,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 100,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 101,
    guests: 7,
    beds: 6,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 102,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 103,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 105,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 106,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 108,
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 110,
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 113,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 114,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 116,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 117,
    guests: 10,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 118,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 119,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 120,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 121,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 123,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 124,
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 125,
    guests: 15,
    beds: 11,
    bath: 3,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 126,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 128,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 129,
    guests: 15,
    beds: 11,
    bath: 3,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 130,
    guests: 3,
    beds: 2,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 131,
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 132,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 114,
    guests: 15,
    beds: 11,
    bath: 3,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 105,
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 80,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 1,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 43,
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 89,
    guests: 7,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 37,
    guests: 3,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 16,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 71,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 128,
    guests: 7,
    beds: 6,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 130,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 117,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 109,
    guests: 4,
    beds: 4,
    bath: 2,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 126,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 108,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 38,
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 42,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 66,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 110,
    guests: 8,
    beds: 7,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 91,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 99,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 62,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 46,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 65,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 72,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 7,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 121,
    guests: 5,
    beds: 3,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 20,
    guests: 15,
    beds: 9,
    bath: 3,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 100,
    guests: 3,
    beds: 3,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 76,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 104,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 11,
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 124,
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 35,
    guests: 7,
    beds: 3,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 44,
    guests: 14,
    beds: 7,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "false",
    water: "false",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 96,
    guests: 14,
    beds: 12,
    bath: 3,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 95,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 69,
    guests: 8,
    beds: 7,
    bath: 1,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 64,
    guests: 10,
    beds: 7,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 73,
    guests: 5,
    beds: 4,
    bath: 3,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 114,
    guests: 12,
    beds: 2,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 67,
    guests: 7,
    beds: 6,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 120,
    guests: 12,
    beds: 5,
    bath: 3,
    wifi: "false",
    kitchen: "false",
    heat: "false",
    water: "true",
    shower: "true",
    firepit: "false",
  },
  {
    listing_id: 87,
    guests: 7,
    beds: 2,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "true",
  },
  {
    listing_id: 7,
    guests: 7,
    beds: 6,
    bath: 2,
    wifi: "false",
    kitchen: "true",
    heat: "false",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 13,
    guests: 5,
    beds: 2,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 17,
    guests: 6,
    beds: 5,
    bath: 2,
    wifi: "true",
    kitchen: "false",
    heat: "true",
    water: "true",
    shower: "false",
    firepit: "false",
  },
  {
    listing_id: 21,
    guests: 14,
    beds: 8,
    bath: 1,
    wifi: "false",
    kitchen: "true",
    heat: "true",
    water: "false",
    shower: "true",
    firepit: "true",
  },
  {
    listing_id: 100,
    guests: 8,
    beds: 7,
    bath: 1,
    wifi: "true",
    kitchen: "true",
    heat: "true",
    water: "true",
    shower: "true",
    firepit: "true",
  },
];
